# Notebook 2 : Pandas avancé

In [3]:
import pandas as pd

## Tennis

Nous considérons les données des résultats des matchs de tennis masculin des tournois de Roland Garros et Wimbledon en 2013. La liste des variables et leur signification se trouvent sur [cette page](https://archive.ics.uci.edu/dataset/300/tennis+major+tournament+match+statistics) dans la section *Additional Variable Information*.

1. Commencer par charger le jeu de données relatif au tournoi de Roland Garros dans un dataframe `rg` à partir du fichier `rolandgarros2013.csv`.

In [4]:
rg = pd.read_csv("~/work/D-pot-test/DATA/rolandgarros2013.csv", sep=',')

In [5]:
rg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 42 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player1  125 non-null    object
 1   Player2  125 non-null    object
 2   Round    125 non-null    int64
 3   Result   125 non-null    int64
 4   FNL.1    125 non-null    int64
 5   FNL.2    125 non-null    int64
 6   FSP.1    125 non-null    int64
 7   FSW.1    125 non-null    int64
 8   SSP.1    125 non-null    int64
 9   SSW.1    125 non-null    int64
 10  ACE.1    125 non-null    int64
 11  DBF.1    123 non-null    float64
 12  WNR.1    125 non-null    int64
 13  UFE.1    125 non-null    int64
 14  BPC.1    125 non-null    int64
 15  BPW.1    125 non-null    int64
 16  NPA.1    125 non-null    int64
 17  NPW.1    125 non-null    int64
 18  TPW.1    125 non-null    int64
 19  ST1.1    125 non-null    int64
 20  ST2.1    125 non-null    int64
 21  ST3.1    123 non-null    float64
 22  ST4.1    51 non-null     float64
 23  ST5.1    22 non-null     float64
 24  FSP.2    125 non-null    int64
 25  FSW.2    125 non-null    int64
 26  SSP.2    125 non-null    int64
 27  SSW.2    125 non-null    int64
 28  ACE.2    125 non-null    int64
 29  DBF.2    123 non-null    float64
 30  WNR.2    125 non-null    int64
 31  UFE.2    125 non-null    int64
 32  BPC.2    125 non-null    int64
 33  BPW.2    125 non-null    int64
 34  NPA.2    125 non-null    int64
 35  NPW.2    125 non-null    int64
 36  TPW.2    125 non-null    int64
 37  ST1.2    125 non-null    int64
 38  ST2.2    125 non-null    int64
 39  ST3.2    123 non-null    float64
 40  ST4.2    51 non-null     float64
 41  ST5.2    22 non-null     float64
dtypes: float64(8), int64(32), object(2)
memory usage: 41.1+ KB

In [6]:
rg.head()

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,7,7,14,18,88,6,6,6.0,NaN,NaN
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,1,16,22,25,106,3,3,5.0,NaN,NaN
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,10,18,19,27,139,3,3,6.0,6.0,3.0
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,4,13,33,43,149,6,3,7.0,6.0,NaN
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,4,7,12,13,93,6,6,6.0,NaN,NaN

2. Afficher les noms des demi-finalistes.

In [7]:
finalistes = rg[['Player1', 'Player2']]
finalistes

                 Player1                  Player2
0    Pablo Carreno-Busta            Roger Federer
1       Somdev Devvarman  Daniel Munoz-De La Nava
2           Tobias Kamke            Paolo Lorenzi
3       Julien Benneteau        Ricardas Berankis
4            Lukas Lacko              Sam Querrey
..                   ...                      ...
120         Rafael Nadal       Stanislas Wawrinka
121       Novak Djokovic               Tommy Haas
122         David Ferrer       Jo-Wilfried Tsonga
123       Novak Djokovic             Rafael Nadal
124         Rafael Nadal             David Ferrer

[125 rows x 2 columns]

3. Calculer le nombre moyen d'aces par match dans le tournoi.

In [8]:
rg["Aces"]=rg["ACE.1"]+rg["ACE.2"]
rg["Aces"].agg("mean")

np.float64(12.688)

4. Combien y a-t-il eu d'aces par match en moyenne à chaque niveau du tournoi ?

In [11]:
rg.groupby("Round")["Aces"].mean()

Round
1    13.476190
2    13.193548
3    12.562500
4     9.125000
5     7.000000
6    10.000000
7     6.000000
Name: Aces, dtype: float64

5. Filtrer les matchs pour lesquels au moins une des variables `DBF.1` et `DBF.2` est manquante.

In [12]:
rg[ rg["DBF.1"].isna() | rg["DBF.2"].isna()]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Aces
56,Simone Bolelli,Yen-Hsun Lu,1,0,0,3,63,33,37,12,...,11,4,6,78,6,6,2.0,NaN,NaN,8
63,Somdev Devvarman,Roger Federer,2,0,0,3,61,19,39,16,...,14,19,30,88,6,6,6.0,NaN,NaN,5

6. Remplacer les valeurs manquantes de `DBF.1` par zéro avec la méthode `loc`.

In [13]:
rg.loc[rg["DBF.1"].isna(), "DBF.1"] = 0

7. Remplacer les valeurs manquantes de `DBF.2` par zéro avec la méthode `fillna`.

In [16]:
rg["DBF.2"] = rg["DBF.2"].fillna(0)

8. Extraire la liste des participants à partir des colonnes `Player1` et `Player2`. Une façon de faire consiste à utiliser `concat` et la méthode `drop_duplicates` pour obtenir le résultat sous la forme d'une série et de la convertir en dataframe avec la méthode `to_frame`.

In [22]:
players = pd.concat([rg['Player1'], rg['Player2']]) \
                 .drop_duplicates() \
                 .to_frame(name='Player') \
                 .reset_index(drop = True)

In [29]:
players

                  Player
0    Pablo Carreno-Busta
1       Somdev Devvarman
2           Tobias Kamke
3       Julien Benneteau
4            Lukas Lacko
..                   ...
122          Yen-Hsun Lu
123      Grigor Dimitrov
124          Guido Pella
125         David Goffin
126     Janko Tipsarevic

[127 rows x 1 columns]

9. Écrire une fonction `n_match` qui prend une chaîne de caractères `joueur` en entrée et retourne le nombre de matchs disputés par le joueur.

In [27]:
def n_match(joueur):
    return ((rg['Player1'] == joueur) | (rg['Player2'] == joueur)).sum()

n_match("Rafael Nadal")

np.int64(7)

In [28]:
rg[ (rg['Player1'] == "Rafael Nadal") | (rg['Player2'] == "Rafael Nadal")]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Aces
47,Rafael Nadal,Daniel Brands,1,1,3,1,84,74,16,12,...,4,25,40,115,6,6,4.0,3.0,NaN,12
86,Rafael Nadal,Martin Klizan,2,1,3,1,74,55,26,10,...,7,15,28,90,6,3,3.0,3.0,NaN,11
105,Rafael Nadal,Fabio Fognini,3,1,3,0,78,52,22,14,...,11,17,31,111,6,4,4.0,NaN,NaN,8
115,Rafael Nadal,Kei Nishikori,4,1,3,0,69,39,31,16,...,4,8,16,65,4,1,3.0,NaN,NaN,1
120,Rafael Nadal,Stanislas Wawrinka,5,1,3,0,75,40,25,11,...,5,16,30,64,2,3,1.0,NaN,NaN,8
123,Novak Djokovic,Rafael Nadal,6,0,2,3,67,76,33,30,...,16,15,26,177,6,3,6.0,6.0,9.0,11
124,Rafael Nadal,David Ferrer,7,1,3,0,70,43,30,11,...,12,10,14,72,3,2,3.0,NaN,NaN,6

10. Utiliser les deux question précédentes et la méthode `apply` pour compter le nombre de matchs que chaque participant a disputé et ordonner le résultat par ordre décroissant.

In [31]:
players["n_match"] = players["Player"].apply(n_match)
players

                  Player  n_match
0    Pablo Carreno-Busta        1
1       Somdev Devvarman        2
2           Tobias Kamke        2
3       Julien Benneteau        3
4            Lukas Lacko        1
..                   ...      ...
122          Yen-Hsun Lu        1
123      Grigor Dimitrov        3
124          Guido Pella        2
125         David Goffin        1
126     Janko Tipsarevic        2

[127 rows x 2 columns]

11. Charger maintenant le jeu de données relatif au tournoi de Wimbledon dans un dataframe `wb` à partir du fichier `wimbledon2013.csv`.

In [33]:
wb = pd.read_csv("~/work/D-pot-test/DATA/wimbledon2013.csv", sep=',')
wb

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
0,B.Becker,A.Murray,1,0,0,3,59,29,41,14,...,10,5,23,17,NaN,6,6,6,NaN,NaN
1,J.Ward,Y-H.Lu,1,0,1,3,62,77,38,35,...,15,2,46,39,NaN,6,6,7,7.0,NaN
2,N.Mahut,J.Hajek,1,1,3,0,72,44,28,10,...,1,0,19,12,NaN,2,4,3,NaN,NaN
3,T.Robredo,A.Bogomolov Jr.,1,1,3,0,77,40,23,12,...,0,0,22,13,NaN,2,2,4,NaN,NaN
4,R.Haase,M.Youzhny,1,0,0,3,68,61,32,15,...,21,3,44,30,NaN,6,7,7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,D.Ferrer,J.Del Potro,5,0,0,3,68,45,32,17,...,8,3,21,17,NaN,6,6,7,NaN,NaN
110,N.Djokovic,T.Berdych,5,1,3,0,61,42,39,21,...,2,2,31,21,NaN,6,4,3,NaN,NaN
111,J.Janowicz,A.Murray,6,0,1,3,55,54,45,27,...,13,5,36,22,NaN,6,6,6,6.0,NaN
112,N.Djokovic,J.Del Potro,6,1,3,2,69,102,31,21,...,7,2,37,25,NaN,5,6,6,7.0,3.0
113,N.Djokovic,A.Murray,7,0,0,3,65,40,35,15,...,17,7,37,26,NaN,6,7,6,NaN,NaN

12. Ajouter une colonne `Tournoi` dans les dataframes `rg` et `wb` contenant respectivement les chaînes de caractères `"RG"` et `"WB"`.

In [34]:
rg["Tournoi"] = "RG"
wb["Tournoi"] = "WB"

13. Concaténer les deux dataframes dans un nouveau dataframe `tennis`.

In [ ]:
tennis = pd.concat([rg,wb], ignore_index=True)
tennis

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Aces,Tournoi
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,14,18,88.0,6,6,6.0,NaN,NaN,11.0,RG
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,22,25,106.0,3,3,5.0,NaN,NaN,7.0,RG
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,19,27,139.0,3,3,6.0,6.0,3.0,10.0,RG
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,33,43,149.0,6,3,7.0,6.0,NaN,27.0,RG
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,12,13,93.0,6,6,6.0,NaN,NaN,14.0,RG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,D.Ferrer,J.Del Potro,5,0,0,3,68,45,32,17,...,21,17,NaN,6,6,7.0,NaN,NaN,NaN,WB
110,N.Djokovic,T.Berdych,5,1,3,0,61,42,39,21,...,31,21,NaN,6,4,3.0,NaN,NaN,NaN,WB
111,J.Janowicz,A.Murray,6,0,1,3,55,54,45,27,...,36,22,NaN,6,6,6.0,6.0,NaN,NaN,WB
112,N.Djokovic,J.Del Potro,6,1,3,2,69,102,31,21,...,37,25,NaN,5,6,6.0,7.0,3.0,NaN,WB
113,N.Djokovic,A.Murray,7,0,0,3,65,40,35,15,...,37,26,NaN,6,7,6.0,NaN,NaN,NaN,WB

14. Utiliser le dataframe `tennis` pour comparer le nombre moyen d'aces par match à chaque niveau du tournoi à Roland Garros et à Wimbledon. Afficher le résultat en format large.

In [38]:
tennis["Aces"] = tennis["ACE.1"] + tennis["ACE.2"]
tennis.groupby("Tournoi")["Aces"].mean()

Tournoi
RG    12.688000
WB    22.438596
Name: Aces, dtype: float64

15. Quelle différence y a-t-il dans le format des noms des joueurs entre les dataframes `rg` et `wb` ?

In [40]:
rg[['Player1', 'Player2']].head()

               Player1                  Player2
0  Pablo Carreno-Busta            Roger Federer
1     Somdev Devvarman  Daniel Munoz-De La Nava
2         Tobias Kamke            Paolo Lorenzi
3     Julien Benneteau        Ricardas Berankis
4          Lukas Lacko              Sam Querrey

In [ ]:
wb[['Player1', 'Player2']].head()

     Player1          Player2
0   B.Becker         A.Murray
1     J.Ward           Y-H.Lu
2    N.Mahut          J.Hajek
3  T.Robredo  A.Bogomolov Jr.
4    R.Haase        M.Youzhny

16. Construire un dataframe `rg_victoires` avec les trois colonnes suivantes pour le tournoi de Roland Garros :
- `joueur` : nom du joueur tel qu'il est donné dans `rg`,
- `nom_joueur` : nom de famille du joueur uniquement,
- `n_victoire` : nombre de matchs gagnés dans le tournoi.

In [41]:
players

                  Player  n_match
0    Pablo Carreno-Busta        1
1       Somdev Devvarman        2
2           Tobias Kamke        2
3       Julien Benneteau        3
4            Lukas Lacko        1
..                   ...      ...
122          Yen-Hsun Lu        1
123      Grigor Dimitrov        3
124          Guido Pella        2
125         David Goffin        1
126     Janko Tipsarevic        2

[127 rows x 2 columns]

In [44]:
def n_victoire(df, joueur):
    n_victoire1 = len(df[ (rg["Player1"] == joueur) & (df["Result"] == 1) ])  
    n_victoire2 = len(df[ (rg["Player2"] == joueur) & (df["Result"] == 1) ])  
    return n_victoire1 + n_victoire2

print(n_victoire(rg, "Roger Federer"))

1

In [ ]:
rg_victoires = (
pd.concat([rg["Player1"], rg["Player2"]])

)

17. Construire un dataframe `wb_victoires` avec les trois colonnes suivantes pour le tournoi de Wimbledon :
- `joueur` : nom du joueur tel qu'il est donné dans `wb`,
- `nom_joueur` : nom de famille du joueur uniquement,
- `n_victoire` : nombre de matchs gagnés dans le tournoi.

18. Faire une jointure entre `rg_victoires` et `wb_victoires` sur la colonne `nom_joueur` pour comparer le nombre de victoires par tournoi pour chaque joueur. Expliquer la différence de résultat selon que la jointure est à gauche, à droite, intérieure ou extérieure.