# Notebook 6 : MongoDB

In [2]:
# Décommenter la ligne suivante pour installer pymongo
%pip install pymongo

Collecting pymongo
  Downloading pymongo-4.16.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 4.8 MB/s  0:00:00 eta 0:00:01
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
Installing collected packages: dnspython, pymongo
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pymongo]m1/2 [pymongo]
Successfully installed dnspython-2.8.0 pymongo-4.16.0
Note: you may need to restart the kernel to use updated packages.

In [15]:
import json

import pandas as pd
import pymongo

client = pymongo.MongoClient(
    # Coller ici la configuration donnée dans Onyxia
    'mongodb://user-yelakel-ensae:xvtf492musm0qse6p0eu@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017/defaultdb'
)

db = client.defaultdb

In [7]:
db

Database(MongoClient(host=['mongodb-0.mongodb-headless:27017', 'mongodb-1.mongodb-headless:27017'], document_class=dict, tz_aware=False, connect=True), 'defaultdb')

## Planètes de Star Wars

Nous considérons ici les données des planètes de *Star Wars* exportées à la fin du *Notebook 4*. Le fichier `planets.json` est également disponible dans le dossier des jeux de données.

1. Accéder à une collection `planets` et s'assurer qu'elle est vide grâce à la méthode `count_documents`.

In [ ]:
# Collection planets
planets = db["planets"]
planets.drop()


# Vérifier le nombre de documents
nb = planets.count_documents({})

print("Nombre de documents :", nb)

Nombre de documents : 0

2. Importer les données des planètes dans la collection `planets`.

In [20]:
planets.insert_many(
        pd.read_json("/home/onyxia/work/D-pot-test/DATA/planets.json", lines = True)
        .to_dict(orient="records")
)

InsertManyResult([ObjectId('69d8eb7e0ba70b11364e9d7d'), ObjectId('69d8eb7e0ba70b11364e9d7e'), ObjectId('69d8eb7e0ba70b11364e9d7f'), ObjectId('69d8eb7e0ba70b11364e9d80'), ObjectId('69d8eb7e0ba70b11364e9d81'), ObjectId('69d8eb7e0ba70b11364e9d82'), ObjectId('69d8eb7e0ba70b11364e9d83'), ObjectId('69d8eb7e0ba70b11364e9d84'), ObjectId('69d8eb7e0ba70b11364e9d85'), ObjectId('69d8eb7e0ba70b11364e9d86'), ObjectId('69d8eb7e0ba70b11364e9d87'), ObjectId('69d8eb7e0ba70b11364e9d88'), ObjectId('69d8eb7e0ba70b11364e9d89'), ObjectId('69d8eb7e0ba70b11364e9d8a'), ObjectId('69d8eb7e0ba70b11364e9d8b'), ObjectId('69d8eb7e0ba70b11364e9d8c'), ObjectId('69d8eb7e0ba70b11364e9d8d'), ObjectId('69d8eb7e0ba70b11364e9d8e'), ObjectId('69d8eb7e0ba70b11364e9d8f'), ObjectId('69d8eb7e0ba70b11364e9d90'), ObjectId('69d8eb7e0ba70b11364e9d91'), ObjectId('69d8eb7e0ba70b11364e9d92'), ObjectId('69d8eb7e0ba70b11364e9d93'), ObjectId('69d8eb7e0ba70b11364e9d94'), ObjectId('69d8eb7e0ba70b11364e9d95'), ObjectId('69d8eb7e0ba70b11364e9d96'), ObjectId('69d8eb7e0ba70b11364e9d97'), ObjectId('69d8eb7e0ba70b11364e9d98'), ObjectId('69d8eb7e0ba70b11364e9d99'), ObjectId('69d8eb7e0ba70b11364e9d9a'), ObjectId('69d8eb7e0ba70b11364e9d9b'), ObjectId('69d8eb7e0ba70b11364e9d9c'), ObjectId('69d8eb7e0ba70b11364e9d9d'), ObjectId('69d8eb7e0ba70b11364e9d9e'), ObjectId('69d8eb7e0ba70b11364e9d9f'), ObjectId('69d8eb7e0ba70b11364e9da0'), ObjectId('69d8eb7e0ba70b11364e9da1'), ObjectId('69d8eb7e0ba70b11364e9da2'), ObjectId('69d8eb7e0ba70b11364e9da3'), ObjectId('69d8eb7e0ba70b11364e9da4'), ObjectId('69d8eb7e0ba70b11364e9da5'), ObjectId('69d8eb7e0ba70b11364e9da6'), ObjectId('69d8eb7e0ba70b11364e9da7'), ObjectId('69d8eb7e0ba70b11364e9da8'), ObjectId('69d8eb7e0ba70b11364e9da9'), ObjectId('69d8eb7e0ba70b11364e9daa'), ObjectId('69d8eb7e0ba70b11364e9dab'), ObjectId('69d8eb7e0ba70b11364e9dac'), ObjectId('69d8eb7e0ba70b11364e9dad'), ObjectId('69d8eb7e0ba70b11364e9dae'), ObjectId('69d8eb7e0ba70b11364e9daf'), ObjectId('69d8eb7e0ba70b11364e9db0'), ObjectId('69d8eb7e0ba70b11364e9db1'), ObjectId('69d8eb7e0ba70b11364e9db2'), ObjectId('69d8eb7e0ba70b11364e9db3'), ObjectId('69d8eb7e0ba70b11364e9db4'), ObjectId('69d8eb7e0ba70b11364e9db5'), ObjectId('69d8eb7e0ba70b11364e9db6'), ObjectId('69d8eb7e0ba70b11364e9db7'), ObjectId('69d8eb7e0ba70b11364e9db8')], acknowledged=True)

3. Exporter l'ensemble des planètes sans l'identifiant `_id` dans un dataframe à l'aide du résultat de la méthode `find`.

In [21]:
# Récupérer les documents sans le champ _id
cursor = planets.find({}, {"_id": 0})

# Convertir en liste puis en DataFrame
df = pd.DataFrame(list(cursor))

# Afficher le résultat
print(df.head())

                     edited              climate surface_water      name  \
0  2014-12-20T20:58:18.411Z                 arid             1  Tatooine
1  2014-12-20T20:58:18.420Z            temperate            40  Alderaan
2  2014-12-20T20:58:18.421Z  temperate, tropical             8  Yavin IV
3  2014-12-20T20:58:18.423Z               frozen           100      Hoth
4  2014-12-20T20:58:18.425Z                murky             8   Dagobah

  diameter rotation_period                   created  \
0    10465              23  2014-12-09T13:50:49.641Z
1    12500              24  2014-12-10T11:35:48.479Z
2    10200              24  2014-12-10T11:37:19.144Z
3     7200              23  2014-12-10T11:39:13.934Z
4     8900              23  2014-12-10T11:42:22.590Z

                              terrain       gravity orbital_period  \
0                              desert    1 standard            304
1               grasslands, mountains    1 standard            364
2                 jungle, rainforests    1 standard           4818
3  tundra, ice caves, mountain ranges  1.1 standard            549
4                      swamp, jungles           N/A            341

   population residents films             url
0      200000        []    []  /api/planets/1
1  2000000000        []    []  /api/planets/2
2        1000        []    []  /api/planets/3
3     unknown        []    []  /api/planets/4
4     unknown        []    []  /api/planets/5

4. Rechercher les planètes dont la période de rotation est égale à 25. Quel est le problème ? Combien y en a-t-il ?

In [22]:
result = list(planets.find({
    "$or": [
        {"rotation_period": 25},
        {"rotation_period": "25"}
    ]
}))

print(len(result))

5

5. Même question mais en limitant la réponse aux clés `name`, `rotation_period`, `orbital_period` et `diameter`.

In [23]:
result = list(planets.find(
    {
        "$or": [
            {"rotation_period": 25},
            {"rotation_period": "25"}
        ]
    },
    {
        "_id": 0,
        "name": 1,
        "rotation_period": 1,
        "orbital_period": 1,
        "diameter": 1
    }
))

print(len(result))
print(result)

5
[{'name': 'Cato Neimoidia', 'diameter': '0', 'rotation_period': '25', 'orbital_period': '278'}, {'name': 'Corellia', 'diameter': '11000', 'rotation_period': '25', 'orbital_period': '329'}, {'name': 'Dantooine', 'diameter': '9830', 'rotation_period': '25', 'orbital_period': '378'}, {'name': 'Trandosha', 'diameter': '0', 'rotation_period': '25', 'orbital_period': '371'}, {'name': 'Haruun Kal', 'diameter': '10120', 'rotation_period': '25', 'orbital_period': '383'}]

6. Trier les planètes du résultat précédent par diamètre décroissant. Quel est le problème ?

In [24]:
result = list(planets.find(
    {
        "$or": [
            {"rotation_period": 25},
            {"rotation_period": "25"}
        ]
    },
    {
        "_id": 0,
        "name": 1,
        "rotation_period": 1,
        "orbital_period": 1,
        "diameter": 1
    }
).sort("diameter", -1))

print(result)

[{'name': 'Dantooine', 'diameter': '9830', 'rotation_period': '25', 'orbital_period': '378'}, {'name': 'Corellia', 'diameter': '11000', 'rotation_period': '25', 'orbital_period': '329'}, {'name': 'Haruun Kal', 'diameter': '10120', 'rotation_period': '25', 'orbital_period': '383'}, {'name': 'Cato Neimoidia', 'diameter': '0', 'rotation_period': '25', 'orbital_period': '278'}, {'name': 'Trandosha', 'diameter': '0', 'rotation_period': '25', 'orbital_period': '371'}]

7. Vider la collection et importer à nouveau les données mais en faisant les corrections suivantes au préalable (un dataframe intermédiaire pourra être utilisé pour manipuler les données avant leur insertion) :
- convertir les valeurs numériques (gérer les cas `unknown`),
- supprimer les variables `created`, `edited`, `films`, `gravity`, `residents` et `url`.
- transformer les variables `climate` et `terrain` en listes de chaînes de caractères plutôt qu'une longue chaîne séparée par des virgules.

8. Reprendre la question 6 et vérifier que le résultat est maintenant correct.

In [25]:
pd.DataFrame(
    planets.find(
        filter = {"rotation_period":25},
        projection = {"_id" : False}
    )
)

Empty DataFrame
Columns: []
Index: []

9. Extraire les planètes dont le nom commence par `T`.

In [ ]:
result = list(planets.find(
    {"name": {"$regex": "^T"}},
    {"_id": 0, "name": 1}
))

print(result)

pd.DataFrame(list(cursor))

[{'name': 'Tatooine'}, {'name': 'Trandosha'}, {'name': 'Toydaria'}, {'name': 'Troiken'}, {'name': 'Tund'}, {'name': 'Tholoth'}]

10. Extraire les planètes dont le diamètre est strictement supérieur à 10000 et où se trouvent des montagnes.

In [27]:
cursor = planets.find(
    {
        "diameter": {"$gt": 10000},
        "terrain": "mountains"
    },
    {"_id": 0}
)

import pandas as pd
df = pd.DataFrame(list(cursor))

print(df)
print(len(df))

Empty DataFrame
Columns: []
Index: []
0

11. Rechercher puis supprimer la planète dont le nom est `unknown`.

In [28]:
pd.DataFrame(
    planets.find(filter={"name":"unknown"})
)

,_id,edited,climate,surface_water,name,diameter,rotation_period,created,terrain,gravity,orbital_period,population,residents,films,url
0,69d8eb7e0ba70b11364e9d98,2014-12-20T20:58:18.466Z,unknown,unknown,unknown,0,0,2014-12-15T12:25:59.569Z,unknown,unknown,0,unknown,[],[],/api/planets/28

In [29]:
planets.delete_one({"name":"unknown"})

DeleteResult({'n': 1, 'opTime': {'ts': Timestamp(1775827625, 1), 't': 2}, 'electionId': ObjectId('7fffffff0000000000000002'), 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1775827625, 1), 'signature': {'hash': b'O\xde{\xe0\xff\x18\xde9\xbelo)\x94\x05\x91\x81C%\xb2\x8d', 'keyId': 7627100183771217926}}, 'operationTime': Timestamp(1775827625, 1)}, acknowledged=True)

12. Mettre en œuvre un pipeline d'agrégation qui calcule le nombre de planètes dans la collection. Verifier le résultat avec la méthode `count_documents`.

13. Mettre en œuvre un pipeline d'agrégation pour calculer le diamètre moyen et la somme des populations des planètes contenant des glaciers.